In [1]:
import numpy as np

In [2]:
my_list1 = [1,2,3,4]

In [3]:
my_array1 = np.array(my_list1)

In [5]:
my_array1

array([1, 2, 3, 4])

In [6]:
my_list2 = [11,22,33,44]


In [7]:
my_lists = [my_list1, my_list2]

In [8]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [9]:
my_array2 = np.array(my_lists)

In [10]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [11]:
my_array2.shape

(2L, 4L)

In [12]:
my_array2.dtype

dtype('int32')

In [13]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [14]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [16]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [17]:
5.0/2

2.5

In [18]:
from __future__ import division

In [19]:
5/2

2.5

In [20]:
a1 = np.array([[1,2,3,4],[8,9,10,11]])

In [21]:
a1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

a1*a1

In [23]:
1/a1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.125     ,  0.11111111,  0.1       ,  0.09090909]])

In [24]:
a1 = np.arange(0,11) 

In [25]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
a1[0]

0

In [27]:
a1[1:5]

array([1, 2, 3, 4])

In [28]:
a1[1:5] = 100


In [29]:
a1

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [31]:
a1 = np.arange(0,11)

In [32]:
slice = a1[0:6]

In [33]:
slice

array([0, 1, 2, 3, 4, 5])

In [34]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
slice[:] = 99

In [36]:
a1

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [37]:
a2 = a1.copy()


In [38]:
a2

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [39]:
a1 = np.array([[1,2,3,4],[8,9,10,11],[12,13,14,15]])

In [40]:
a1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
a1[1][1]

9

In [42]:
a1[1]

array([ 8,  9, 10, 11])

In [44]:
slice = a1[:2][:2]

In [45]:
slice

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [46]:
slice = a1[:2,:2]

In [47]:
slice

array([[1, 2],
       [8, 9]])

In [48]:
a1[-1]

array([12, 13, 14, 15])

In [50]:
a2 = np.zeros((10,10))

In [51]:
a2

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [52]:
size = a2.shape[1]

In [53]:
size

10L

In [54]:
for i in range(size):
    a2[i] = i

In [55]:
a2

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [59]:
test = np.array(([1,2,3,4,5],[6,7,8,9,10]))

In [60]:
test

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [61]:
test[0] = 1

In [62]:
test

array([[ 1,  1,  1,  1,  1],
       [ 6,  7,  8,  9, 10]])

In [63]:
test[[1,0]]

array([[ 6,  7,  8,  9, 10],
       [ 1,  1,  1,  1,  1]])

In [64]:
test[1,0]

6

In [65]:
#array transposition

In [66]:
a = np.arange(50).reshape((10,5))

In [67]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [68]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [2]:
#continued on next